mongodb:
  username: root
  password: Password123$
  host: 127.0.0.1
  port: 27017
  database: project-fish
  collection: resources

rabbitmq:
  username: root
  password: Password123$

proxy:
  url: http://127.0.0.1:8082