mongodb:
  username: root
  password: Password123$
  host: 127.0.0.1
  port: 27017
  database: project-fish
  request_collection: resources
  content_collection: content

rabbitmq:
  username: root
  password: Password123$
  host: 127.0.0.1
  port: 5672
  url_queue: pf_urlqueue

redis:
  host: 127.0.0.1
  port: 6379
  database: 0

browser:
  max_tabs: 2
  pageload_timeout: 30
  executable_path: /usr/bin/google-chrome-stable