mongodb:
  username: root
  password: Password123$
  host: 127.0.0.1
  port: 27017
  database: project-fish
  request_collection: resources
  content_collection: content
  certificate_collection: certificates

rabbitmq:
  username: root
  password: Password123$
  host: 127.0.0.1
  port: 5672
  url_queue: pf_urlqueue

redis:
  host: 127.0.0.1
  port: 6379
  content_database: 0
  certificate_database: 1

browser:
  max_tabs: 1
  pageload_timeout: 30
  browser_timeout: 300
  min_request_wait: 4
  max_content_size: 10MB
  executable_path: /usr/bin/google-chrome-stable

maxminddb:
  country_database_path: /home/kali/workspace/project-fish/worker/config/GeoLite2-Country.mmdb
  asn_database_path: /home/kali/workspace/project-fish/worker/config/GeoLite2-ASN.mmdb